# Standards: 1.2
---
- name: Delete userdata iso
  when: item.stat.exists
  file:
    path: "/var/lib/libvirt/userdata/{{ item.item.name }}.iso"
    state: absent
  tags:
    - libvirt
    - machines

- name: Create userdata dir
  file:
    path: "/var/lib/libvirt/userdata/{{ item.item.name }}"
    state: directory
  tags:
    - libvirt
    - machines

- name: Create user-data file
  template:
    src: machines/userdata.j2
    dest: "/var/lib/libvirt/userdata/{{ item.item.name }}/user-data"
  tags:
    - libvirt
    - machines

- name: Create meta-data file
  template:
    src: machines/metadata.j2
    dest: "/var/lib/libvirt/userdata/{{ item.item.name }}/meta-data"
  tags:
    - libvirt
    - machines

- name: Create network-config file
  template:
    src: machines/network.j2
    dest: "/var/lib/libvirt/userdata/{{ item.item.name }}/network-config"
  tags:
    - libvirt
    - machines

- name: Generate userdata image
  command: |
    genisoimage -J -r -output /var/lib/libvirt/userdata/{{ item.item.name }}.iso -volid cidata /var/lib/libvirt/userdata/{{ item.item.name }}/user-data /var/lib/libvirt/userdata/{{ item.item.name }}/meta-data /var/lib/libvirt/userdata/{{ item.item.name }}/network-config
  args:
    creates: "/var/lib/libvirt/userdata/{{ item.item.name }}.iso"
  tags:
    - libvirt
    - machines

- name: Fix image perms
  file:
    path: "/var/lib/libvirt/userdata/{{ item.item.name }}.iso"
    owner: libvirt-qemu
    group: kvm
    mode: 0660
  tags:
    - libvirt
    - machines

- name: Delete userdata dir
  file:
    path: "/var/lib/libvirt/userdata/{{ item.item.name }}"
    state: absent
  tags:
    - libvirt
    - machines

...
